{% set version = "0.2.2" %}

{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.8").split(".")[0] | int %}
{% endif %}

package:
  name: openmm-nonbonded-slicing
  version: {{ version }}

source:
  url: https://github.com/craabreu/openmm-nonbonded-slicing/archive/v{{ version }}.tar.gz
  sha256: 1d88f618ae5bff1fb1c09aa9fa34a943c5a62b2cbe77684fd1835d4b11eb29b3
build:
  number: 2
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  skip: true  # [win]
  skip: true  # [aarch64 and cuda_compiler_version not in (undefined, 'None')]
  rpaths:
    - lib/

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=1.19                           # [build_platform != target_platform]
    - swig <4.1                              # [build_platform != target_platform]
    - openmm >=8.0.0                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version not in (undefined, 'None')]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    {% if cuda_major >= 12 %}
    - cuda-driver-dev
    - cuda-nvrtc-dev
    - libcufft-dev
    {% endif %}
    - cmake
    - make
  host:
    - python
    - pip
    - swig <4.1
    - openmm >=8.0.0
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [osx]
    {% if cuda_major >= 12 %}
    - cuda-driver-dev
    - cuda-cudart-dev
    - cuda-nvrtc-dev
    - cuda-nvtx-dev
    - cuda-nvml-dev
    - libcublas-dev
    - libcufft-dev
    - libcurand-dev
    {% endif %}
  run:
    - python
    - {{ pin_compatible('openmm', max_pin='x.x') }}
    - ocl-icd  # [linux]
    - ocl-icd-system  # [linux]
    - khronos-opencl-icd-loader  # [osx]
    - ocl_icd_wrapper_apple      # [osx]

test:
  imports:
    - nonbondedslicing
  commands: |
    cd ${CONDA_PREFIX}/share/openmm-nonbonded-slicing/tests
    ls -al
    set +e
    summary=""
    exitcode=0
    for f in Test*; do
      if [[ $f == *Cuda* || $f == *OpenCL* ]]; then
        continue
      fi
      echo "Running $f..."
      ./${f}
      thisexitcode=$?
      summary+="\n${f}: "
      if [[ $thisexitcode == 0 ]]; then summary+="OK"; else summary+="FAILED"; fi
      ((exitcode+=$thisexitcode))
    done
    echo "-------"
    echo "Summary"
    echo "-------"
    echo -e "${summary}"
    exit $exitcode

about:
  home: https://github.com/craabreu/openmm-nonbonded-slicing
  summary: 'An OpenMM plugin for slicing nonbonded interactions'
  description: |
    This plugin contains the SlicedNonbondedForce class, a variant of
    OpenMM's NonbondedForce. By partitioning all particles among disjoint
    subsets, the total potential energy becomes a linear combination of
    contributions from pairs of subsets.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://craabreu.github.io/openmm-nonbonded-slicing
  dev_url: https://github.com/craabreu/openmm-nonbonded-slicing

extra:
  recipe-maintainers:
    - craabreu
    - jananzhu
